config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :images
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/image.rb
class Image < ApplicationRecord
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController

  #Esto es un callBack, "before_action" invoca a un metodo antes de cada accion
  before_action :set_image, only: [:show, :edit, :update, :destroy]

	def index
    puts '############### estoy en el index ############'
		@images = Image.all
	end

	def new
		#Nota: cuando se llama a la accion "new" 
		#este automaticamente busca la vista "new.html.erb"
		#Una vez oprimido el boton del formulario, este llama a la accion "create"

		@image = Image.new
	end

	def create
		#render plain: params[:image].inspect
		@image = Image.new image_params
		@image.save # guarda la imagen en la base de datos

		redirect_to @image 
	end

	def show
    puts '############### estoy en show ############'
  end

	def edit
		#Nota: cuando se llama a la accion "edit"
		#este automaticamente busca la vista "edit.html.erb"
		#Una vez oprimido el boton del formulario, este llama a la accion "update"
	end

	def update
		@image.update image_params
		redirect_to @image
	end

  def destroy
    puts '############### estoy en el destroy ############'
    @image.destroy
    redirect_to images_path
  end

	private
	def image_params
		params.require(:image).permit(:description)
  end

  def set_image
    #NOTA: este metodo es llamado por un callBack (before_action)
    #por lo tanto este metodo es llamado cada vez que se llaman a los metodos :show, :edit, :update, :destroy
    @image = Image.find params[:id] #busca una imagen desde la base de datos con un "id" (ingresado desde la url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/images_helper.rb
module ImagesHelper
end

app/views/images/_form.html.erb
<!-- Esto es un parcial de codigo -->
<!-- Se usa para reutilizar codigo -->
<!-- Es llamado por otras vistas-->

<%= form_for @image do |f|%>
  <%= f.label :description %> <br>
  <%= f.text_field :description%>
  <br>

  <%=f.submit%>
  <<% end %>

app/views/images/_image.erb
<!--esto es un parcial-->
<!--Es un fragmento de codigo que es llamado por otras vistas-->

<%= image.id %>
<%= image.description %>
<%=  link_to 'Edit', edit_image_path(image) %>
<%=  link_to 'Destroy', image, method: :delete, data: { confirm: 'sure?'} %>
<br>

app/views/images/edit.html.erb
<p>Editar Imagen</p>


<!-- <%= form_for @image do |f|%>
  <%= f.label :description %> <br>
  <%= f.text_field :description%>
  <br>
  &lt;!&ndash;cuando el ususrio oprime el boton, es llama a la accion "Update" del controlador&ndash;&gt;

  <%=f.submit%>
  <<% end %>-->


<!-- llama a un parcial "_form.html.erb" que contiene un formulario-->
<%= render 'form' %>

app/views/images/index.html.erb
<!--muestra un listado de todos los datos-->
<!--para ello automaticamente se llama a un  "_image.html.erb" con el fin de ahorrar codigo-->
<%= render @images %>

app/views/images/new.html.erb
<p>Hola desde mi vista new :D</p>

<!-- ########## codigo comentado #########-->
<!--
<%= form_for :image, url: images_path do |f|%>
	<%= f.label :description %> <br>
	<%= f.text_field :description%>
	<br>
-->
  <!--cuando el ususrio oprime el boton, es llama a la accion "create" del controlador-->
<!--
  <%=f.submit%> <
<% end %>
-->

<!-- #########################################-->

<!-- llama a un parcial "_form.html.erb" que contiene un formulario-->
<%= render 'form' %>

app/views/images/show.html.erb
<%= @image.description %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Railsgram</title>
    <%= csrf_meta_tags %>

<%#     <%= stylesheet_link_tag    'default', media: 'all', 'data-turbolinks-track': 'reload' %> 
<%# <%= javascript_include_tag 'default', 'data-turbolinks-track': 'reload' %> 
  </head>

  <body>
    <%= yield %>
  </body>
</html>